const express = require("express");
const ExcelJs = require("exceljs");
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const jsonData = [
  {
    id: 1,
    firstName: "Liam",
    lastName: "Smith",
    age: 28,
    email: "liam.smith@example.com",
    password: "Password@1",
    number: "+1-555-0101",
  },
  {
    id: 2,
    firstName: "Olivia",
    lastName: "Johnson",
    age: 34,
    email: "olivia.johnson@example.com",
    password: "Password@2",
    number: "+1-555-0102",
  },
  {
    id: 3,
    firstName: "Noah",
    lastName: "Williams",
    age: 22,
    email: "noah.williams@example.com",
    password: "Password@3",
    number: "+1-555-0103",
  },
  {
    id: 4,
    firstName: "Emma",
    lastName: "Brown",
    age: 29,
    email: "emma.brown@example.com",
    password: "Password@4",
    number: "+1-555-0104",
  },
  {
    id: 5,
    firstName: "Oliver",
    lastName: "Jones",
    age: 45,
    email: "oliver.jones@example.com",
    password: "Password@5",
    number: "+1-555-0105",
  },
  {
    id: 6,
    firstName: "Ava",
    lastName: "Garcia",
    age: 31,
    email: "ava.garcia@example.com",
    password: "Password@6",
    number: "+1-555-0106",
  },
  {
    id: 7,
    firstName: "Elijah",
    lastName: "Miller",
    age: 27,
    email: "elijah.miller@example.com",
    password: "Password@7",
    number: "+1-555-0107",
  },
  {
    id: 8,
    firstName: "Sophia",
    lastName: "Davis",
    age: 40,
    email: "sophia.davis@example.com",
    password: "Password@8",
    number: "+1-555-0108",
  },
  {
    id: 9,
    firstName: "James",
    lastName: "Rodriguez",
    age: 33,
    email: "james.rodriguez@example.com",
    password: "Password@9",
    number: "+1-555-0109",
  },
  {
    id: 10,
    firstName: "Charlotte",
    lastName: "Martinez",
    age: 25,
    email: "charlotte.martinez@example.com",
    password: "Password@10",
    number: "+1-555-0110",
  },
  {
    id: 11,
    firstName: "William",
    lastName: "Hernandez",
    age: 38,
    email: "william.hernandez@example.com",
    password: "Password@11",
    number: "+1-555-0111",
  },
  {
    id: 12,
    firstName: "Amelia",
    lastName: "Lopez",
    age: 26,
    email: "amelia.lopez@example.com",
    password: "Password@12",
    number: "+1-555-0112",
  },
  {
    id: 13,
    firstName: "Benjamin",
    lastName: "Gonzalez",
    age: 41,
    email: "benjamin.gonzalez@example.com",
    password: "Password@13",
    number: "+1-555-0113",
  },
  {
    id: 14,
    firstName: "Mia",
    lastName: "Wilson",
    age: 23,
    email: "mia.wilson@example.com",
    password: "Password@14",
    number: "+1-555-0114",
  },
  {
    id: 15,
    firstName: "Lucas",
    lastName: "Anderson",
    age: 30,
    email: "lucas.anderson@example.com",
    password: "Password@15",
    number: "+1-555-0115",
  },
  {
    id: 16,
    firstName: "Harper",
    lastName: "Thomas",
    age: 35,
    email: "harper.thomas@example.com",
    password: "Password@16",
    number: "+1-555-0116",
  },
  {
    id: 17,
    firstName: "Henry",
    lastName: "Taylor",
    age: 44,
    email: "henry.taylor@example.com",
    password: "Password@17",
    number: "+1-555-0117",
  },
  {
    id: 18,
    firstName: "Evelyn",
    lastName: "Moore",
    age: 29,
    email: "evelyn.moore@example.com",
    password: "Password@18",
    number: "+1-555-0118",
  },
  {
    id: 19,
    firstName: "Alexander",
    lastName: "Jackson",
    age: 37,
    email: "alexander.jackson@example.com",
    password: "Password@19",
    number: "+1-555-0119",
  },
  {
    id: 20,
    firstName: "Abigail",
    lastName: "Martin",
    age: 24,
    email: "abigail.martin@example.com",
    password: "Password@20",
    number: "+1-555-0120",
  },
  {
    id: 21,
    firstName: "Michael",
    lastName: "Lee",
    age: 52,
    email: "michael.lee@example.com",
    password: "Password@21",
    number: "+1-555-0121",
  },
  {
    id: 22,
    firstName: "Emily",
    lastName: "Perez",
    age: 31,
    email: "emily.perez@example.com",
    password: "Password@22",
    number: "+1-555-0122",
  },
  {
    id: 23,
    firstName: "Daniel",
    lastName: "Thompson",
    age: 43,
    email: "daniel.thompson@example.com",
    password: "Password@23",
    number: "+1-555-0123",
  },
  {
    id: 24,
    firstName: "Elizabeth",
    lastName: "White",
    age: 27,
    email: "elizabeth.white@example.com",
    password: "Password@24",
    number: "+1-555-0124",
  },
  {
    id: 25,
    firstName: "Jacob",
    lastName: "Harris",
    age: 36,
    email: "jacob.harris@example.com",
    password: "Password@25",
    number: "+1-555-0125",
  },
  {
    id: 26,
    firstName: "Sofia",
    lastName: "Sanchez",
    age: 21,
    email: "sofia.sanchez@example.com",
    password: "Password@26",
    number: "+1-555-0126",
  },
  {
    id: 27,
    firstName: "Logan",
    lastName: "Clark",
    age: 39,
    email: "logan.clark@example.com",
    password: "Password@27",
    number: "+1-555-0127",
  },
  {
    id: 28,
    firstName: "Avery",
    lastName: "Ramirez",
    age: 32,
    email: "avery.ramirez@example.com",
    password: "Password@28",
    number: "+1-555-0128",
  },
  {
    id: 29,
    firstName: "Jackson",
    lastName: "Lewis",
    age: 47,
    email: "jackson.lewis@example.com",
    password: "Password@29",
    number: "+1-555-0129",
  },
  {
    id: 30,
    firstName: "Ella",
    lastName: "Robinson",
    age: 26,
    email: "ella.robinson@example.com",
    password: "Password@30",
    number: "+1-555-0130",
  },
  {
    id: 31,
    firstName: "Sebastian",
    lastName: "Walker",
    age: 33,
    email: "sebastian.walker@example.com",
    password: "Password@31",
    number: "+1-555-0131",
  },
  {
    id: 32,
    firstName: "Scarlett",
    lastName: "Young",
    age: 28,
    email: "scarlett.young@example.com",
    password: "Password@32",
    number: "+1-555-0132",
  },
  {
    id: 33,
    firstName: "Jack",
    lastName: "Allen",
    age: 49,
    email: "jack.allen@example.com",
    password: "Password@33",
    number: "+1-555-0133",
  },
  {
    id: 34,
    firstName: "Grace",
    lastName: "King",
    age: 30,
    email: "grace.king@example.com",
    password: "Password@34",
    number: "+1-555-0134",
  },
  {
    id: 35,
    firstName: "Aiden",
    lastName: "Wright",
    age: 25,
    email: "aiden.wright@example.com",
    password: "Password@35",
    number: "+1-555-0135",
  },
  {
    id: 36,
    firstName: "Chloe",
    lastName: "Scott",
    age: 36,
    email: "chloe.scott@example.com",
    password: "Password@36",
    number: "+1-555-0136",
  },
  {
    id: 37,
    firstName: "Matthew",
    lastName: "Torres",
    age: 42,
    email: "matthew.torres@example.com",
    password: "Password@37",
    number: "+1-555-0137",
  },
  {
    id: 38,
    firstName: "Victoria",
    lastName: "Nguyen",
    age: 24,
    email: "victoria.nguyen@example.com",
    password: "Password@38",
    number: "+1-555-0138",
  },
  {
    id: 39,
    firstName: "Samuel",
    lastName: "Hill",
    age: 51,
    email: "samuel.hill@example.com",
    password: "Password@39",
    number: "+1-555-0139",
  },
  {
    id: 40,
    firstName: "Riley",
    lastName: "Flores",
    age: 29,
    email: "riley.flores@example.com",
    password: "Password@40",
    number: "+1-555-0140",
  },
  {
    id: 41,
    firstName: "David",
    lastName: "Green",
    age: 34,
    email: "david.green@example.com",
    password: "Password@41",
    number: "+1-555-0141",
  },
  {
    id: 42,
    firstName: "Luna",
    lastName: "Adams",
    age: 22,
    email: "luna.adams@example.com",
    password: "Password@42",
    number: "+1-555-0142",
  },
  {
    id: 43,
    firstName: "Joseph",
    lastName: "Nelson",
    age: 46,
    email: "joseph.nelson@example.com",
    password: "Password@43",
    number: "+1-555-0143",
  },
  {
    id: 44,
    firstName: "Zoey",
    lastName: "Baker",
    age: 27,
    email: "zoey.baker@example.com",
    password: "Password@44",
    number: "+1-555-0144",
  },
  {
    id: 45,
    firstName: "Carter",
    lastName: "Hall",
    age: 39,
    email: "carter.hall@example.com",
    password: "Password@45",
    number: "+1-555-0145",
  },
  {
    id: 46,
    firstName: "Penelope",
    lastName: "Rivera",
    age: 31,
    email: "penelope.rivera@example.com",
    password: "Password@46",
    number: "+1-555-0146",
  },
  {
    id: 47,
    firstName: "Owen",
    lastName: "Campbell",
    age: 28,
    email: "owen.campbell@example.com",
    password: "Password@47",
    number: "+1-555-0147",
  },
  {
    id: 48,
    firstName: "Layla",
    lastName: "Mitchell",
    age: 25,
    email: "layla.mitchell@example.com",
    password: "Password@48",
    number: "+1-555-0148",
  },
  {
    id: 49,
    firstName: "Wyatt",
    lastName: "Carter",
    age: 35,
    email: "wyatt.carter@example.com",
    password: "Password@49",
    number: "+1-555-0149",
  },
  {
    id: 50,
    firstName: "Nora",
    lastName: "Roberts",
    age: 30,
    email: "nora.roberts@example.com",
    password: "Password@50",
    number: "+1-555-0150",
  },
];

// console.log(key);

app.get("/download/excel", async (req, res) => {
  try {
    const workbook = new ExcelJs.Workbook();

    const worksheet = workbook.addWorksheet("My Users");

    if (jsonData.length > 0) {
      const column = Object.keys(jsonData[0]);
      worksheet.columns = column.map((col) => {
        return {
          header: col.toUpperCase(),
          key: col,
          width: col.length + 10,
        };
      });
    }

    const passwordCol = worksheet.getColumn("password");
    passwordCol.hidden = true; // hide password column
    
    worksheet.addRows(jsonData);

    worksheet.getRow(1).font = { bold: true };

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );

    res.setHeader("Content-Disposition", "attachment; filename=" + "user.xlsx");

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    console.log(error.message);
  }
});
app.listen(3002, () => {
  console.log("Server run on the 3002");
});
